### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by encukou** [encukou/gitpathlib#1]
Dump of one-line ideas that don't need their own issue (yet).
Contributors: Please file a separate issue if you pick one of these up! Preferably comment here that you're interested, so we avoid duplicate work.

- [ ] Don't require pygit2 (just shell out to git if it's not installed -- for cases you can't install libgit2 and don't worry about performance)
- [ ] Test constructors on bare and non-bare repos
- [ ] Don't subclass in `__init__.py`
- [ ] Nicer `__str__` and `__repr__`
- [ ] Backends should use their own namespace (`_gpb_`?)
- [ ] Test with Unicode (and non-UTF-8) paths
- [ ] Test with subprojects
- [ ] Test without pygit2

Maintaining:

- [ ] Host docs on Read the Docs
- [ ] Test on Travis
- [ ] Add CONTRIBUTING & CHANGELOG
